### ISSUE TITLE
Windows issue: The directory name is invalid when using msys2 (e.g. Git Bash)

### ISSUE THREAD

**Issue by ionelmc** [mgedmin/check-manifest#64] opened 2015-12-20 09:32 UTC
I get something like this on Appveyor:

```
C:\projects\python-hunter>CALL C:\Python27\Scripts\tox   || EXIT 1 
GLOB sdist-make: C:\projects\python-hunter\setup.py 
check create: C:\projects\python-hunter\.tox\check 
check installdeps: docutils, check-manifest, flake8, readme, pygments 
check installed: bleach==1.4.2,check-manifest==0.30,docutils==0.12,flake8==2.5.1,html5lib==0.9999999,mccabe==0.3.1,pep8==1.5.7,pyflakes==1.0.0,Pygments==2.0.2,readme==0.6.0,six==1.10.0,wheel==0.24.0 
check runtests: PYTHONHASHSEED='632'
check runtests: commands[0] | python setup.py check --strict --metadata --restructuredtext
running check
check runtests: commands[1] | check-manifest C:\projects\python-hunter 
could not run ['git', 'ls-files', '-z']: [WinError 267] The directory name is invalid
ERROR: InvocationError: 'C:\\projects\\python-hunter\\.tox\\check\\Scripts\\check-manifest.EXE C:\\projects\\python-hunter' 
___________________________________ summary ___________________________________
ERROR:   check: commands failed
Command exited with code 1
```

https://ci.appveyor.com/project/ionelmc/python-hunter/build/master-66/job/fd169ykntce3ugva#L81

**Comment by mgedmin** [comment] 2015-12-21 06:33
Interesting.  The error comes straight from `subprocess.Popen(['git', 'ls-files', '-z', cwd=None, stdin=..., stdout=..., stderr=...)`.  The working directory at that point should be `c:\projects\python-hunter`.

I've no idea what's happening.

**Comment by mgedmin** [comment] 2015-12-21 08:26
I cannot reproduce this on my Windows VM:
![ekrano nuotrauka is 2015-12-21 10-25-48](https://cloud.githubusercontent.com/assets/159967/11926402/40015a76-a7cd-11e5-8f7c-2d8e3f260969.png)

**Comment by ionelmc** [comment] 2015-12-21 08:34
Well this is strange, it's passing now: https://ci.appveyor.com/project/ionelmc/python-hunter/build/master-78/job/lgc97j2jwjjc9u4r

Sorry for noise :confused:

**Comment by brechtm** [comment] 2016-12-22 23:05
I'm also experiencing this problem. Windows 10, Python 3.5.2, check-manifest 0.34. Also running in a tox environment.

**Comment by brechtm** [comment] 2016-12-22 23:10
Interesting observation: running check-manifest manually (not in a tox env) works when run from bash (MSYS2) but not from cmd!

**Comment by brechtm** [comment] 2016-12-22 23:34
When running from cmd, `git.exe` was not in my `PATH`, resulting in *could not run ['git', 'ls-files', '-z']: [WinError 2] The system cannot find the **file** specified*. So this is not the cause of the original problem.

**Comment by brechtm** [comment] 2016-12-22 23:49
Running tox from cmd, check-manifest succeeds. Running tox from bash yields the error. The run function is being passed a bad path: `cwd='../../../../../c/Users/Brecht/Documents/Opqode/rinohtype/doc/_build/html'`

I'm not yet sure how this path is being constructed...

**Comment by mgedmin** [comment] 2016-12-27 06:22
The only time I'm passing a `cwd` to `run()` is when I need to run `git ls-files` on each git submodule.  Clearly, something's going wrong there.

It may be useful to know your `git` version, among other things.  Also, could you perhaps run the check-manifest test-suite and see if you get any test failures? I have a test for the git submodule support.

**Comment by mgedmin** [comment] 2016-12-27 09:07
I can reproduce this:
```
mg@LANGAS: /c/buildslave/workspace/check-manifest-on-windows [git:(52293a7...)] $ tox -e py27
GLOB sdist-make: C:\buildslave\workspace\check-manifest-on-windows\setup.py
py27 inst-nodeps: C:\buildslave\workspace\check-manifest-on-windows\.tox\dist\check-manifest-0.35.dev0.zip
py27 installed: You are using pip version 7.1.2, however version 9.0.1 is available.,You should consider upgrading via the 'python -m pip install --upgrade pip' command.,-f https://debesis.gedmin.as/wheels/,check-manifest==0.35.dev0,funcsigs==1.0.2,mock==2.0.0,nose==1.3.7,pbr==1.10.0,six==1.10.0,wheel==0.26.0
py27 runtests: PYTHONHASHSEED='852'
py27 runtests: commands[0] | nosetests
....S.F.............................E........................................................................
======================================================================
ERROR: test_get_versioned_files_with_git_submodules (tests.TestGit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\buildslave\workspace\check-manifest-on-windows\tests.py", line 948, in test_get_versioned_files_with_git_submodules
    get_vcs_files(),
  File "C:\buildslave\workspace\check-manifest-on-windows\check_manifest.py", line 455, in get_vcs_files
    return normalize_names(vcs.get_versioned_files())
  File "C:\buildslave\workspace\check-manifest-on-windows\check_manifest.py", line 325, in get_versioned_files
    files += add_prefix_to_each(subdir, cls._git_ls_files(subdir))
  File "C:\buildslave\workspace\check-manifest-on-windows\check_manifest.py", line 330, in _git_ls_files
    output = run(['git', 'ls-files', '-z'], encoding=cls._encoding, cwd=cwd)
  File "C:\buildslave\workspace\check-manifest-on-windows\check_manifest.py", line 149, in run
    raise Failure("could not run %s: %s" % (command, e))
Failure: could not run ['git', 'ls-files', '-z']: [Error 267] The directory name is invalid
```

This error doesn't happen in my Jenkins, or if I run `c:\Python27\Scripts\tox.exe -e py27` from `cmd.exe`.  It does happen if I run `cmd.exe` from inside a git bash shell, and then run tox from it.

**Comment by mgedmin** [comment] 2016-12-27 12:19
I use `git submodule --quiet foreach -- 'printf "%s/%s\n" $toplevel $path'` to see all submodule paths.  This prints `Paths\Like\This` in cmd.exe, but `/paths/like/this` in git bash.  Python's subprocess.Popen() doesn't like cwd='/path/like/this` on Windows.

**Comment by mgedmin** [comment] 2016-12-27 12:45
If you have Git version 2.11 or newer, could you test if my proposed fix in #77 helps?

(I'm still on Git 2.9 and figuring out how to upgrade Git on Windows is not what I want to be doing during my lunch break.)

**Comment by mgedmin** [comment] 2016-12-27 12:57
Oh, interesting: the tests pass if I `export TOX_TOXENV_PASSENV=MSYSTEM` in my bash shell before I run `tox`.

**Comment by mgedmin** [comment] 2016-12-27 13:04
I'm going to close this, unless somebody can verify that they see this issue pop up when not using `tox`.

The workaround is to make sure you configure `tox` to include `MSYSTEM` in `passenv`.

**Closed by mgedmin** 2016-12-27 13:04 UTC
Labels: help-needed

**Comment by brechtm** [comment] 2017-02-22 10:35
Thanks Marius! Passing `MSYSTEM` makes things work.
