### ISSUE TITLE
tox runs ok but can't build - src directory problem

### ISSUE THREAD

**Issue by Neon22** [mgedmin/check-manifest#154] opened 2022-03-21 02:08 UTC
I have a basic project. (with a subpackage)
Was developed without a src buffer directory. I have now inserted one to try to make packaging more robust. 
But now = problems. So I guess it was a good idea...

`tox` works: checks flake8, runs pytest, builds docs. Indicates success
`python -m build` also successfully builds a whl and tar.gz file
but package no longer works locally and cannot be imported.
I was using `pip install --user -e .`

I want to get ready for uploading to Pypi.

check-manifest tells me all my files are in the wrong place but not how to fix it.
Is there a way `check-manifest` can help me work out what's wrong

```
pyweaving/
    tests/
    docs/
    src/
        pyweaving/
            __init__.py
            foo.py
            data/
            generators/
                __init__.py
               bar.py

    setup.py (just the stub code)
    setup.cfg
```
MANIFEST.in
```
include tox.ini
recursive-include docs *
recursive-include tests *

exclude coverage.rc
graft src

prune docs/_build
recursive-exclude * __pycache__
recursive-exclude * *.py[co]
```
setup.cfg
```
[metadata]
name = pyweaving
version = 0.8
license = MIT
description = Python Weaving Tools
long_description = file: README.rst
keywords = weaving handweaving wif draft pattern

[options]
python_requires = >=3.8
zip_safe = False
packages = find_namespace:
package_dir =
    =src
include_package_data = True
install_requires =
	Pillow>=2.1.0
        svgwrite>=1.4.1

[options.entry_points]
console_scripts =
	pyweaving = pyweaving.cmd:main

[options.packages.find]
where=src
```
tox.ini - even though its not used by check-manifest (as I understand it)
```
[tox]
envlist = py39, docs

[testenv]
commands =
# do flake8 but don't stop
	-flake8
	coverage run -m pytest --basetemp="{envtmpdir}" {posargs}
	coverage html
	coverage report
deps =
	pytest
	flake8
	coverage

[flake8]
# E203 whitespace before :
# E501 Max line length 79
# E722 Bare exceptions
# W503 linebreaks before binary operator
# F841 local var never used
extend-ignore = E203, E501, E722
#max-complexity = 10
max-line-length = 127
statistics = True
extend-exclude =
    setup.py,
	conf.py,
	__init__.py
	tests

[pytest]
addopts = -ra -q
testpaths =
    tests

[testenv:docs]
basepython = python
changedir = docs
deps =
    sphinx
    sphinx_rtd_theme
	svgwrite
commands =
    sphinx-build -W -a -b html -d {envtmpdir}/doctrees . {envtmpdir}/html
```
Error message from check-manifest
```
>>>check-manifest -u -v
listing source files under version control: 43 files and directories
building an sdist: pyweaving-0.8.tar.gz: 64 files and directories
some files listed as being under source control are missing:
  coverage.rc
  pyweaving/Color.py
  pyweaving/Draft.py
  pyweaving/Drawstyle.py
  pyweaving/__init__.py
  pyweaving/cmd.py
  pyweaving/data/Arial.ttf
  pyweaving/data/styles.json
  pyweaving/generators/__init__.py
  pyweaving/generators/collected_tartans.txt
  pyweaving/generators/dither.py
  pyweaving/generators/raster.py
  pyweaving/generators/satin.py
  pyweaving/generators/tartan.py
  pyweaving/generators/twill.py
  pyweaving/instructions.py
  pyweaving/render-presvg.py
  pyweaving/render.py
  pyweaving/repeats.py
  pyweaving/wif.py
copying source files to a temporary directory
building a clean sdist
['C:\\Python39\\python.exe', 'setup.py', 'sdist', '-d', 'C:\\Users\\Asus\\AppData\\Local\\Temp\\check-manifest-ps3zl3q8-sdist'] failed (status 1):
running sdist
running egg_info
error: error in 'egg_base' option: 'src' does not exist or is not a directory
```
and I can't find coverage.rc anywhere.
When I do `pip install --user -e .` I get errors like
`AssertionError: Egg-link c:\users\asus\documents\github\pyweaving does not match installed location of pyweaving (at c:\users\asus\documents\github\pyweaving\src)`

**Comment by mgedmin** [comment] 2022-03-22 10:11
I see nothing wrong at a glance.  `graft src` should not be needed, setuptools includes the Python source files by default.

> some files listed as being under source control are missing:

hints that the mismatch is not in your Python packaging, but between your version control metadata and your filesystem contents.

What version control system do you use?  Have you committed your changes after moving the source files into the `src/` subdirectory?  My guess is that you haven't, and that's the cause of the issue.

**Comment by Neon22** [comment] 2022-03-22 10:38
I'm using git but you're right. I was trying to get it working before committing it.
I did not realize it needed the commit.

**Comment by mgedmin** [comment] 2022-05-23 12:50
>  I did not realize it needed the commit.

Technically I think a `git add` would be sufficient.

**Closed** 2022-05-23 12:49 UTC
Labels: question
